config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'mangas#index'
  resources :mangas, only: [:index, :show] do
    collection do
      get 'search_results'
    end
  end
  resources :authors, only: [:index, :show]
  resources :genres, only: [:index, :show]
  resources :characters, only: [:show]
  get 'about', to: 'pages#about'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :manga_authors
  has_many :mangas, through: :manga_authors

  # Validations
  validates :name, presence: true, uniqueness: true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :manga

  # Validations
  validates :name, :role, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :manga_genres
  has_many :mangas, through: :manga_genres

  # Validations
  validates :name, presence: true, uniqueness: true
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :characters
  has_many :manga_genres
  has_many :genres, through: :manga_genres
  has_many :manga_authors
  has_many :authors, through: :manga_authors

  # Validations
  validates :title, :synopsis, :chapters, :release_date, presence: true
  validates :chapters, numericality: { only_integer: true }
  validates :title, uniqueness: true
end

app/models/manga_author.rb
class MangaAuthor < ApplicationRecord
  # 1.5 - many-to-many association
  belongs_to :manga
  belongs_to :author
end

app/models/manga_genre.rb
class MangaGenre < ApplicationRecord
  # 1.5 - many-to-many association 
  belongs_to :manga
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
    @character = Character.find(params[:id])
    @manga = @character.manga
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @mangas = @genre.mangas
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  def index
    @mangas = Manga.all
  end

  def show
    @manga = Manga.find(params[:id])
  end

  def search_results
    @query = params[:query]
    @mangas = Manga.where("title LIKE ?", "%#{@query}%")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/index.html.erb
<h1 class="title has-text-centered">All Authors</h1>
<table class="table is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.name, author_path(author) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/authors/show.html.erb
<div class="section">
  <div class="container">
    <%= link_to 'Back to All Authors', authors_path, class: 'button is-small is-light' %>
    <h1 class="title has-text-centered"><%= @author.name %></h1>

    <div class="content">
      <h2 class="subtitle has-text-centered">Mangas</h2>
      <div class="buttons is-centered">
        <% if @author.mangas.any? %>
          <% @author.mangas.each do |manga| %>
            <%= link_to manga.title, manga_path(manga), class: 'button is-link is-light' %>
          <% end %>
        <% else %>
          <span>No mangas available</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<div class="section">
    <div class="container">
        <%= link_to 'Back to Manga', manga_path(@manga), class: 'button is-small is-light' %>
    <h1 class="title has-text-centered"><%= @character.name %></h1>

    <div class="content has-text-centered">
      <%= image_tag @character.image_url, alt: @character.name if @character.image_url.present? %>
      <p><strong>Role:</strong> <%= @character.role %></p>
      <h2 class="subtitle has-text-centered">Manga Appearances</h2>
      <div class="buttons is-centered">
        <%= link_to @manga.title, manga_path(@manga), class: 'button is-link is-light' %>
      </div>
    </div>
    </div>
</div>

app/views/genres/index.html.erb
<h1 class="title">All Genres</h1>
<table class="table is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= link_to genre.name, genre_path(genre) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/genres/show.html.erb
<%= link_to 'Back to All Genres', genres_path, class: 'button is-small is-light' %>
<h1 class="title has-text-centered"><%= @genre.name %> Mangas</h1>

<table class="table is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Release Date</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'mangas/manga_list', collection: @mangas, as: :manga %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Manga On Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# Bulma CSS %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
  </head>

  <body>
    <header class="navbar is-dark">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to 'Manga On Rails', root_path, class: 'navbar-item' %>
        </div>
        <div class="navbar-menu">
          <div class="navbar-start">
            <%= link_to 'Home', root_path, class: 'navbar-item' %>
            <%= link_to 'About', about_path, class: 'navbar-item' %>
            <%= link_to 'Authors', authors_path, class: 'navbar-item' %>
            <%= link_to 'Genres', genres_path, class: 'navbar-item' %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <%= form_with(url: search_results_mangas_path, method: "get", local: true) do %>
                <div class="field has-addons">
                  <div class="control">
                    <%= text_field_tag(:query, params[:query], class: 'input', placeholder: 'Search for Mangas') %>
                  </div>
                  <div class="control">
                    <%= submit_tag("Search", class: 'button is-info') %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </header>
    <main class="section" style="background-color:rgb(25, 24, 24);">
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/mangas/_manga_list.html.erb
<tr>
  <td><%= image_tag manga.small_image_url, alt: manga.title if manga.small_image_url.present? %></td>
  <td><%= link_to manga.title, manga_path(manga), class: 'has-text-link' %></td>
  <td>
    <% manga.authors.each do |author| %>
        <%# Iterate over the author's names, adds comma and space for each author name unless it's the last author %>
      <%= link_to author.name, author_path(author), class: 'has-text-link' %><%= ", " unless author == manga.authors.last %>
    <% end %>
  </td>
  <td><%= manga.release_date %></td>
</tr>

app/views/mangas/index.html.erb
<h1 class="title has-text-centered">All Mangas</h1>
<table class="table is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Author</th>
      <th>Release Date</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'mangas/manga_list', collection: @mangas, as: :manga %>
  </tbody>
</table>

app/views/mangas/search_results.html.erb
<p>
  Your search for '<%= @query %>' returned <%= pluralize(@mangas.size, 'result') %>.
</p>

<table class="table is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Release Date</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'mangas/manga_list', collection: @mangas, as: :manga %>
  </tbody>
</table>

app/views/mangas/show.html.erb
<div class="section">
  <div class="container">
    <%= link_to 'Back to All Mangas', mangas_path, class: 'button is-small is-light' %>
    <h1 class="title has-text-centered"><%= @manga.title %></h1>

    <div class="content has-text-centered">
      <%= image_tag @manga.large_image_url, alt: @manga.title if @manga.large_image_url.present? %>
      <p><strong>Synopsis:</strong> <%= @manga.synopsis %></p>
      <p><strong>Chapters:</strong> <%= @manga.chapters %></p>
      <p><strong>Release Date:</strong> <%= @manga.release_date %></p>

      <h2 class="subtitle has-text-centered">Authors</h2>
      <div class="buttons is-centered">
        <% if @manga.authors.any? %>
          <% @manga.authors.each do |author| %>
            <%= link_to author.name, author_path(author), class: 'button is-link is-light' %>
          <% end %>
        <% else %>
          <span>No authors available</span>
        <% end %>
      </div>

      <h2 class="subtitle has-text-centered">Genres</h2>
      <div class="buttons is-centered">
        <% if @manga.genres.any? %>
          <% @manga.genres.each do |genre| %>
            <%= link_to genre.name, genre_path(genre), class: 'button is-link is-light' %>
          <% end %>
        <% else %>
          <span>No genres available</span>
        <% end %>
      </div>

      <h2 class="subtitle has-text-centered">Characters</h2>
      <div class="buttons is-centered">
        <% if @manga.characters.any? %>
          <% @manga.characters.each do |character| %>
            <%= link_to "#{character.name} - #{character.role}", character_path(character), class: 'button is-link is-light' %>
          <% end %>
        <% else %>
          <span>No characters available</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<!-- filepath: c:\fullstack\Rails\manga_on_rails\app\views\pages\about.html.erb -->
<div class="section">
  <div class="container">
    <h1 class="title has-text-centered">Manga on Rails Data Project</h1>
    <p class="subtitle has-text-centered">Made by Hanz Samonte</p>
    <p class="has-text-centered">
      <a href="https://github.com/Hanz-Ian/manga_on_rails" class="button is-link">View on GitHub!</a>
    </p>

    <div class="content">
      <h2>1 - Gathering and Storing Data</h2>

      <h3>1.1 - Describe Datasets</h3>
      <p>I'll be using the Jikan API to gather data about mangas. The Jikan API is an unofficial MyAnimeList API that provides access to detailed information about mangas, including their titles, synopses, genres, chapters, authors, publication dates, and characters.</p>

      <h4>Data Structure</h4>
      <p>The data from the Jikan API is structured in JSON format and includes the following key fields:</p>
      <ul>
        <li><code>title</code>: The title of the manga.</li>
        <li><code>synopsis</code>: A brief description of the manga.</li>
        <li><code>genres</code>: An array of genres associated with the manga.</li>
        <li><code>chapters</code>: The number of chapters in the manga.</li>
        <li><code>authors</code>: An array of authors who worked on the manga.</li>
        <li><code>published</code>: The publication dates of the manga.</li>
        <li><code>characters</code>: An array of characters associated with the manga.</li>
      </ul>

      <h4>Required Database Tables and Columns</h4>
      <p>To store the manga data, we will create the following database tables:</p>
      <ul>
        <li><strong>Mangas Table</strong>
          <ul>
            <li><code>title</code> (string): The title of the manga.</li>
            <li><code>synopsis</code> (text): A brief description of the manga.</li>
            <li><code>genre</code> (string): A comma-separated list of genres.</li>
            <li><code>chapters</code> (integer): The number of chapters in the manga.</li>
            <li><code>release_date</code> (date): The publication start date of the manga.</li>
          </ul>
        </li>
        <li><strong>Characters Table</strong>
          <ul>
            <li><code>name</code> (string): The name of the character.</li>
            <li><code>description</code> (text): A brief description of the character.</li>
            <li><code>manga_id</code> (integer): Foreign key to the <code>mangas</code> table.</li>
          </ul>
        </li>
        <li><strong>Genres Table</strong>
          <ul>
            <li><code>name</code> (string): The name of the genre.</li>
          </ul>
        </li>
        <li><strong>MangaGenres Table</strong> (Join table for many-to-many relationship between mangas and genres)
          <ul>
            <li><code>manga_id</code> (integer): Foreign key to the <code>mangas</code> table.</li>
            <li><code>genre_id</code> (integer): Foreign key to the <code>genres</code> table.</li>
          </ul>
        </li>
        <li><strong>Authors Table</strong>
          <ul>
            <li><code>name</code> (string): The name of the author.</li>
            <li><code>manga_id</code> (integer): Foreign key to the <code>mangas</code> table.</li>
          </ul>
        </li>
        <li><strong>MangaAuthors Table</strong> (Join table for many-to-many relationship between mangas and authors)
          <ul>
            <li><code>manga_id</code> (integer): Foreign key to the <code>mangas</code> table.</li>
            <li><code>author_id</code> (integer): Foreign key to the <code>authors</code> table.</li>
          </ul>
        </li>
      </ul>

      <h4>Integration</h4>
      <p>The data pulled from the Jikan API will be used to populate the <code>mangas</code>, <code>characters</code>, <code>genres</code>, <code>manga_genres</code>, <code>authors</code>, and <code>manga_authors</code> tables in the database. Each manga entry will include information about its title, synopsis, genres, chapters, authors, and publication dates. The characters associated with each manga will be stored in the <code>characters</code> table, and the genres will be stored in the <code>genres</code> table. The <code>manga_genres</code> join table will establish the many-to-many relationship between mangas and genres. The <code>manga_authors</code> join table will establish the many-to-many relationship between mangas and authors.</p>

      <h3>1.2 - Database ERD</h3>
      <h2>Entity-Relationship Diagram</h2>
      <%= image_tag 'erd.png', alt: 'ERD' %>

      <h3>1.7 - Data Sources</h3>
      <p>The <code>seeds.rb</code> script is used to pull in data from 2 sources into the database. The primary data source is the Jikan API, which provides detailed information about mangas. Additionally, the Faker gem will also be used to generate data for missing fields and for testing.</p>

      <h2>Models</h2>
      <h3>Manga Model</h3>
      <ul>
        <li><code>id</code> (auto increment PK)</li>
        <li><code>title</code> (string)</li>
        <li><code>synopsis</code> (text)</li>
        <li><code>chapters</code> (integer)</li>
        <li><code>release_date</code> (date)</li>
        <li>Will also be part of the many-to-many relationship with Genre</li>
      </ul>

      <h3>Character Model</h3>
      <ul>
        <li><code>id</code> (auto increment PK)</li>
        <li><code>name</code> (string)</li>
        <li><code>role</code> (string)</li>
        <li><code>manga_id</code> (integer, FK)</li>
      </ul>

      <h3>Genre Model</h3>
      <ul>
        <li><code>id</code> (auto increment PK)</li>
        <li><code>name</code> (string)</li>
        <li>Will also be part of the many-to-many relationship with Manga</li>
      </ul>

      <h3>MangaGenre Model</h3>
      <ul>
        <li><code>manga_id</code> (integer, FK)</li>
        <li><code>genre_id</code> (integer, FK)</li>
      </ul>

      <h3>Author Model</h3>
      <ul>
        <li><code>id</code> (auto increment PK)</li>
        <li><code>name</code> (string)</li>
        <li><code>manga_id</code> (integer, FK)</li>
      </ul>

      <h3>MangaAuthor Model</h3>
      <ul>
        <li><code>manga_id</code> (integer, FK)</li>
        <li><code>author_id</code> (integer, FK)</li>
      </ul>

      <h2>Our many-to-many relationship</h2>
      <p>We will end up with a table like this for our Manga to Genre relationship:</p>

      <h3>MangaGenres Table</h3>
      <ul>
        <li><code>manga_id</code> (integer, FK)</li>
        <li><code>genre_id</code> (integer, FK)</li>
      </ul>

      <h3>MangaAuthors Table</h3>
      <ul>
        <li><code>manga_id</code> (integer, FK)</li>
        <li><code>author_id</code> (integer, FK)</li>
      </ul>
    </div>
  </div>
</div>